name: telegram message
on: [push]
jobs:
  telegram:
    name: Telegram Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Send telegram notification
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO_ME }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.event.pusher.name }} has pushed to repository ${{ github.event.repository.name }}
